name: Push Actions
on: [push, pull_request]
jobs:
  test-and-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - '1.23'
          - '1.24'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: go test
        
      # Not sure if we stand to learn much by running build after test here, but it shouldn't cost much either.
      - name: build 
        run: go build
